language: python
sudo: false

python:
  - "2.6"
  - "2.7"
  - "3.4"

addons:
  apt:
    packages:
    - python-dev
    - libxml2-dev
    - libxslt1-dev

install:
  - if [ $TRAVIS_PYTHON_VERSION == 3* ]; then pip install https://github.com/ncclient/ncclient; fi
  - "pip install -r development.txt"
  - "pip install -r requirements.txt"

script: nosetests -v --with-coverage --cover-package=jnpr.junos --cover-inclusive -a unit

after_success:
  coveralls

notifications:
  email: false
