language: python
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

addons:
  apt:
    packages:
    - python-dev
    - libxml2-dev
    - libxslt1-dev

install:
  - "pip install -r development.txt"
  - "pip install -r requirements.txt"
  - "pip install -U git+https://github.com/vnitinv/ncclient.git@sax-parser"

script: nosetests -v --with-coverage --cover-package=jnpr.junos --cover-inclusive -a unit

after_success:
  coveralls

notifications:
  email: false
